export const CFG_OPENAI_API_KEY = "OPENAI_API_KEY";
export const CFG_OPENAI_MODEL = "OPENAI_MODEL";
export const CFG_CHAT_MAX_STEPS = "CHAT_MAX_STEPS";
export const CFG_OPENAI_STORE = "OPENAI_STORE";
export const CFG_CORS_ORIGIN = "CORS_ORIGIN";
